//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSetupTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCIE-1751,BID#0")]
        public string DIODeviceDescription {
            get {
                return ((string)(this["DIODeviceDescription"]));
            }
            set {
                this["DIODeviceDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SiliconSoftware")]
        public string ImageAcquisitionInterface {
            get {
                return ((string)(this["ImageAcquisitionInterface"]));
            }
            set {
                this["ImageAcquisitionInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SerialCommunicationTimeout {
            get {
                return ((int)(this["SerialCommunicationTimeout"]));
            }
            set {
                this["SerialCommunicationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SerCommMaximumNumberOfTrialsForGettingResponse {
            get {
                return ((int)(this["SerCommMaximumNumberOfTrialsForGettingResponse"]));
            }
            set {
                this["SerCommMaximumNumberOfTrialsForGettingResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ImageAcquisitionTimeoutValue {
            get {
                return ((int)(this["ImageAcquisitionTimeoutValue"]));
            }
            set {
                this["ImageAcquisitionTimeoutValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int NumberOfChannelsInIRAndRGBImage {
            get {
                return ((int)(this["NumberOfChannelsInIRAndRGBImage"]));
            }
            set {
                this["NumberOfChannelsInIRAndRGBImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NumberOfChannelsInColorImage {
            get {
                return ((int)(this["NumberOfChannelsInColorImage"]));
            }
            set {
                this["NumberOfChannelsInColorImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfChannelsInMonoImage {
            get {
                return ((int)(this["NumberOfChannelsInMonoImage"]));
            }
            set {
                this["NumberOfChannelsInMonoImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DelayBetweenCommandsInLoadingInitialSettings {
            get {
                return ((int)(this["DelayBetweenCommandsInLoadingInitialSettings"]));
            }
            set {
                this["DelayBetweenCommandsInLoadingInitialSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTimeTakenInStatusLabel {
            get {
                return ((bool)(this["ShowTimeTakenInStatusLabel"]));
            }
            set {
                this["ShowTimeTakenInStatusLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForImproperCalibrationTarget {
            get {
                return ((bool)(this["CheckForImproperCalibrationTarget"]));
            }
            set {
                this["CheckForImproperCalibrationTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int UIROIRectangleWidth {
            get {
                return ((int)(this["UIROIRectangleWidth"]));
            }
            set {
                this["UIROIRectangleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UIROIRectangleHeight {
            get {
                return ((int)(this["UIROIRectangleHeight"]));
            }
            set {
                this["UIROIRectangleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int FocusROIRectangleWidth {
            get {
                return ((int)(this["FocusROIRectangleWidth"]));
            }
            set {
                this["FocusROIRectangleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FocusROIRectangleHeight {
            get {
                return ((int)(this["FocusROIRectangleHeight"]));
            }
            set {
                this["FocusROIRectangleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int WBROIRectangleWidth {
            get {
                return ((int)(this["WBROIRectangleWidth"]));
            }
            set {
                this["WBROIRectangleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WBROIRectangleHeight {
            get {
                return ((int)(this["WBROIRectangleHeight"]));
            }
            set {
                this["WBROIRectangleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int FFCROIRectangleWidth {
            get {
                return ((int)(this["FFCROIRectangleWidth"]));
            }
            set {
                this["FFCROIRectangleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FFCROIRectangleHeight {
            get {
                return ((int)(this["FFCROIRectangleHeight"]));
            }
            set {
                this["FFCROIRectangleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int LICROIRectangleWidth {
            get {
                return ((int)(this["LICROIRectangleWidth"]));
            }
            set {
                this["LICROIRectangleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LICROIRectangleHeight {
            get {
                return ((int)(this["LICROIRectangleHeight"]));
            }
            set {
                this["LICROIRectangleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int NoOfSamplesUsedInFocusStep {
            get {
                return ((int)(this["NoOfSamplesUsedInFocusStep"]));
            }
            set {
                this["NoOfSamplesUsedInFocusStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MinimumFocusLearningRangeRequired {
            get {
                return ((double)(this["MinimumFocusLearningRangeRequired"]));
            }
            set {
                this["MinimumFocusLearningRangeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int FocusPatternCheckReferenceGrayValue {
            get {
                return ((int)(this["FocusPatternCheckReferenceGrayValue"]));
            }
            set {
                this["FocusPatternCheckReferenceGrayValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DarkFieldCorrectionMaximumGrayLevel {
            get {
                return ((int)(this["DarkFieldCorrectionMaximumGrayLevel"]));
            }
            set {
                this["DarkFieldCorrectionMaximumGrayLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double MinThresholdInDeterminingGain {
            get {
                return ((double)(this["MinThresholdInDeterminingGain"]));
            }
            set {
                this["MinThresholdInDeterminingGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public double MaxThresholdInDeterminingGain {
            get {
                return ((double)(this["MaxThresholdInDeterminingGain"]));
            }
            set {
                this["MaxThresholdInDeterminingGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double GainStepInitialValue {
            get {
                return ((double)(this["GainStepInitialValue"]));
            }
            set {
                this["GainStepInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7999")]
        public double GainMaximumRange {
            get {
                return ((double)(this["GainMaximumRange"]));
            }
            set {
                this["GainMaximumRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MaxIterationsInSettingAutomaticGain {
            get {
                return ((int)(this["MaxIterationsInSettingAutomaticGain"]));
            }
            set {
                this["MaxIterationsInSettingAutomaticGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light intensity is not optimum in one or more channels. Cannot perform white bala" +
            "ncing.")]
        public string WhiteBalancingLightIntensityNotOptimumMessage {
            get {
                return ((string)(this["WhiteBalancingLightIntensityNotOptimumMessage"]));
            }
            set {
                this["WhiteBalancingLightIntensityNotOptimumMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WhiteBalancingOffsetFromRefGrayLevel {
            get {
                return ((int)(this["WhiteBalancingOffsetFromRefGrayLevel"]));
            }
            set {
                this["WhiteBalancingOffsetFromRefGrayLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lens is not closed properly. Cannot perform FPN.")]
        public string FPNLightIntensityNotOptimumMessage {
            get {
                return ((string)(this["FPNLightIntensityNotOptimumMessage"]));
            }
            set {
                this["FPNLightIntensityNotOptimumMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light intensity is not optimum in one or more channels. Cannot perform PRNU.")]
        public string PRNULightIntensityNotOptimumMessage {
            get {
                return ((string)(this["PRNULightIntensityNotOptimumMessage"]));
            }
            set {
                this["PRNULightIntensityNotOptimumMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PRNUMinimumGrayLevelOffset {
            get {
                return ((int)(this["PRNUMinimumGrayLevelOffset"]));
            }
            set {
                this["PRNUMinimumGrayLevelOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double CalibDocumentThresholdMinimumLimit {
            get {
                return ((double)(this["CalibDocumentThresholdMinimumLimit"]));
            }
            set {
                this["CalibDocumentThresholdMinimumLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public double CalibDocumentThresholdMaximumLimit {
            get {
                return ((double)(this["CalibDocumentThresholdMaximumLimit"]));
            }
            set {
                this["CalibDocumentThresholdMaximumLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int CalibDocumentWhiteRegionMinimumArea {
            get {
                return ((int)(this["CalibDocumentWhiteRegionMinimumArea"]));
            }
            set {
                this["CalibDocumentWhiteRegionMinimumArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDualLineTriggeredApplet {
            get {
                return ((bool)(this["UseDualLineTriggeredApplet"]));
            }
            set {
                this["UseDualLineTriggeredApplet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Config\\")]
        public string CameraDefaultSettingsFilePath {
            get {
                return ((string)(this["CameraDefaultSettingsFilePath"]));
            }
            set {
                this["CameraDefaultSettingsFilePath"] = value;
            }
        }
    }
}
